
services:
  database:
    image: postgres:10.17
    environment:
      - 'POSTGRES_HOST=${DB_HOST}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/posgresql/data    
volumes:
  pg-data:
